# Generated by Django 5.0.3 on 2024-04-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='permissions',
            field=models.ManyToManyField(related_name='types', to='users.permission'),
        ),
        migrations.DeleteModel(
            name='TypePermission',
        ),
    ]
