# Generated by Django 5.0.3 on 2024-04-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_type_permissions_delete_typepermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
