# Generated by Django 4.2.10 on 2024-04-21 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_permission_identifier'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('name', 'identifier')},
        ),
    ]
