# Generated by Django 4.2.10 on 2024-04-25 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity',
            old_name='location',
            new_name='location_address',
        ),
        migrations.AddField(
            model_name='commodity',
            name='location_coordinates_lat',
            field=models.CharField(default='blabla', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commodity',
            name='location_coordinates_long',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
