# Generated by Django 4.2.10 on 2024-04-21 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_address', models.CharField(max_length=255)),
                ('location_coordinates_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_coordinates_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField()),
                ('images', models.URLField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuestHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_address', models.CharField(max_length=255)),
                ('location_coordinates_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_coordinates_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('number_of_bathrooms', models.IntegerField(default=1)),
                ('number_of_bedrooms', models.IntegerField(default=1)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('accessibility', models.BooleanField(default=False)),
                ('food_type', models.CharField(choices=[('V', 'Vegan'), ('VE', 'Vegetarian'), ('M', 'Meat')], max_length=2)),
                ('images', models.ImageField(blank=True, null=True, upload_to='guesthouses_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='commodity',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
