# Generated by Django 4.2.10 on 2024-04-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0002_rename_location_commodity_location_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='CommodityType',
        ),
    ]
