# Generated by Django 4.2.10 on 2024-04-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('commodities', '0003_remove_attraction_images_remove_guesthouse_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='custom_attribute',
        ),
        migrations.AddField(
            model_name='attraction',
            name='images',
            field=models.ManyToManyField(related_name='attractions', to='images.image'),
        ),
        migrations.AddField(
            model_name='guesthouse',
            name='images',
            field=models.ManyToManyField(related_name='guesthouses', to='images.image'),
        ),
    ]
