# Generated by Django 5.0.3 on 2024-05-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitylog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], default='Success', max_length=12),
        ),
    ]
