# Generated by Django 5.0.3 on 2024-04-22 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitylog', '0002_rename_action_types_activitylog_action_type'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
