# Generated by Django 5.0.3 on 2024-04-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitylog', '0003_alter_activitylog_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='actor_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
