# Generated by Django 5.0.3 on 2024-04-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userinfo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='occupation',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
